### ISSUE TITLE
Webhook controller doesn't handle workflow related events

### ISSUE THREAD

**Issue by happywisepaul** [Kentico/kontent-boilerplate-net#88]
### Brief bug description

Workflow related events cannot be deserialized into WebhookModel making the webhook controller action Index not executed since the model is null

### Repro steps

Cause the following event to be sent to the webhook:
``` json
{
  "data": {
    "items": [
      {
        "item": {
          "id": "76e78624-c7d7-53ae-ab0f-64dfde05e65e"
        },
        "language": {
          "id": "00000000-0000-0000-0000-000000000000"
        },
        "transition_from": {
          "id": "0041a1b3-1820-44d6-bd8a-f252f8f8bf6a"
        },
        "transition_to": {
          "id": "61f60ea5-66e6-4b1e-9c8e-c34e0782f90f"
        }
      }
    ]
  },
  "message": {
    "id": "960a79fc-95b3-42c0-96e3-1493bf6c0193",
    "project_id": "ad8d8eda-c21e-000c-a5e6-7478633c60f3",
    "type": "content_item_variant",
    "operation": "change_workflow_step",
    "api_name": "content_management",
    "created_timestamp": "2019-12-21T00:35:36.2477126Z",
    "webhook_url": "http://2a5a4d10.ngrok.io/webHooks/KenticoKontentWebHook"
  }
}
```

### Expected behavior

There should be support for both type of events either by handling it in different actions or by some other means so both event model to be deserialized by the same action.

### Test environment

 - Platform/OS:  .NET Core 3.1
 - Boilerplate Version [e.g. 4.0.2]
 - SDK version: 12.3.0

**Comment by petrsvihlik** [comment]
@happywisepaul thanks for reporting this!
@sutrkiller can you confirm, please?

**Comment by sutrkiller** [comment]
Hi @happywisepaul,

This is actually expected behaviour.
There are two types of webhook notifications designed for different scenarios. 
The first one is **notifications about changes to the published content** and the other is **notifications about workflow step changes**. 
**Notifications about changes to the published content** are used for example to invalidate the local cache (as demonstrated in this repo). 
In contrast, **notifications about workflow step changes** are typically used for various integrations, e.g. sending email to translators when a content item in default language moves to workflow step "Ready for translation". 
More information [here](https://docs.kontent.ai/tutorials/develop-apps/integrate/using-webhooks-for-automatic-updates).

Can I ask you for more information about your scenario, why you need other webhooks? 
I recommend creating another webhook for notifications about workflow steps with a different URL. You can easily create another model to serialize notifications based on the [documentation](https://docs.kontent.ai/reference/webhooks-reference#a-data-object-for-workflow-events).

**Comment by happywisepaul** [comment]
Thank you for the explanation.  Sorry for the late reply.

> Can I ask you for more information about your scenario, why you need other webhooks?

The motivation is to use workflow notification to invalidate cache in development environment.

I ended up customizing the boilerplate webhook controller by writing my own action method which deserialize the raw POST request into my own model conforming to the workflow related message schema.
