### ISSUE TITLE
Why was the webhook signature action filter rewritten into middleware?

### ISSUE THREAD

**Issue by JanLenoch** [Kentico/kontent-boilerplate-net#95]
### Motivation

[Middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/?view=aspnetcore-3.1) was designed by MS to run for all requests, without the notion of routing or other context of MVC.

Conversely, [action filters](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1) are designed to run for specific controllers/actions.

Given that the webhook secret will never be used throughout the whole app, the [rewrite of the SignatureActionFilter class into a middleware](https://github.com/Kentico/kontent-boilerplate-net/commit/642f60357e830562f2e72fa2c7a95a9b5a54a9a5) makes no sense. The conversion causes that on each and every hit to all controller actions, the request stream is being read and the hash is being calculated, over and over without a use.

### Proposed solution

Revert back to an action filter.

### Additional context

Blocks #93

**Comment by petrsvihlik** [comment]
Not sure why this decision was made... However, the logic is applied only to selected controllers: https://github.com/Kentico/kontent-boilerplate-net/blob/master/src/content/Kentico.Kontent.Boilerplate/Startup.cs#L76

I'll take a closer look at it tomorrow.

**Comment by petrsvihlik** [comment]
Normally, I would agree that having a custom action filter or a custom [authorization filter/handler/policy](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/iauthorizationpolicyprovider?view=aspnetcore-3.1) would be a good approach. However, in this case we need to read the whole body of the webhook in order to calculate the signature. Which doesn't sound like short-circuiting the request pipeline which [MS Docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1) suggest we should be using the action filters for.

Anyway, the necessity of reading the request body for authorization inevitably leads to re-reading of the request body (for the purposes of processing the actual webhook data). Which, when rewinding is not possible, leads to problems such as this: https://github.com/Kentico/kontent-boilerplate-net/issues/84

As described [here](https://devblogs.microsoft.com/aspnet/re-reading-asp-net-core-request-bodies-with-enablebuffering/) rewinding is usually not an option and saving a copy of the stream is not a good idea performance-wise. That's why the article suggests using `EnableBuffering` and that's exactly what @sutrkiller implemented in https://github.com/Kentico/kontent-boilerplate-net/commit/642f60357e830562f2e72fa2c7a95a9b5a54a9a5.

Perhaps, there is a way to implement the signature validation as a filter. However, we should keep performance in mind. I'm open to any pull requests :)
